version: '3.8'
services:

  traefik:
    image: traefik:v2.9
    container_name: traefik_proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=shamilgaliev18@mail.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - my_network
    restart: always

  app:
    build: .
    container_name: crypto_trading_app
    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user_data:/app_user_data
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/trading_db
    privileged: true
    networks:
      - my_network
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.app.rule=Host(`eazy-trade.ru`)"
    - "traefik.http.routers.app.entrypoints=websecure"
    - "traefik.http.routers.app.tls=true"
    - "traefik.http.routers.app.tls.certresolver=myresolver"
    - "traefik.http.services.app.loadbalancer.server.port=8000"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: trading_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    privileged: true
    networks:
      - my_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - my_network

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    privileged: true
    networks:
      - my_network
    restart: always

  redis:
    image: redis:alpine
    networks:
      - my_network
    restart: always

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
