version: '3.8'
services:


  app:
    build: .
    container_name: crypto_trading_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user_data:/app_user_data
  # Монтирование данных пользователей
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/trading_db
    privileged: true
    networks:
      - my_network
    


  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trading_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    privileged: true
    networks:
      - my_network


  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    privileged: true
    networks:
      - my_network


  redis:
    image: redis:alpine
    networks:
      - my_network



volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge

