version: '3.8'
services:
  freqtrade_user_2_strategy_example1:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade_user_2_strategy_example1
    restart: unless-stopped
    volumes:
    - ./user_data/user_2:/freqtrade/user_data
    ports:
    - '3002'
    command: trade --db-url sqlite:////freqtrade/user_data/trades.sqlite --config
      /freqtrade/user_data/example1.json --strategy example1
    logging:
      driver: json-file
      options:
        max-size: 256m
        max-file: '30'
