name: Deploy to Server

on:
  push:
    branches:
      - v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/crypto_trading_app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/crypto_trading_app:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/user/crypto_trading_platform

          echo "🧼 Truncating DB tables (кроме bots_info)..."
          docker exec -i postgres_db psql -U ${{ secrets.DB_USERNAME }} -d trading_db << EOF
          SET session_replication_role = 'replica';
          DO \$\$
          DECLARE 
              r RECORD;
          BEGIN
              FOR r IN (
                  SELECT tablename 
                  FROM pg_tables 
                  WHERE schemaname = 'public' 
                    AND tablename <> 'bots_nfo'
              )
              LOOP
                  EXECUTE 'TRUNCATE TABLE public.' || quote_ident(r.tablename) || ' RESTART IDENTITY CASCADE';
              END LOOP;
          END \$\$;
          SET session_replication_role = 'origin';

          -- 🟢 Заполняем таблицу bots_info
          INSERT INTO bots_info (name, type, pnl, crypto_pairs, description, created_at, updated_at)
          VALUES 
            ('E0V1E', 'FUTURE', 160, 'BTC/USDT', 'Данный бот круто торгует на BTC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            ('ElliotV8_original_ichiv3', 'SPOT', 70, 'ETH/USDT', 'Данный бот хорошо торгует на ETH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            ('every_minute', 'SPOT', 70, 'BTC/USDT', 'Данный бот хорошо торгует на BTC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

          DO \$\$ BEGIN
              RAISE NOTICE 'Таблицы очищены, bots_info заполнена.';
          END \$\$;
          EOF

          echo "♻️ Cleaning up...."
          docker rm -f $(docker ps -aq)
          rm -rf user_data/user_1

          echo "📦 Updating repo..."
          git reset --hard
          git clean -fdX
          git restore .
          git pull

          echo "🚀 Starting containers..."
          docker-compose down
          docker-compose up -d --build

          echo "📊 Importing backtests..."
          docker-compose run --rm app python3 -m app.load_backtests

          pgrep -f notify.py | xargs -r kill
          setsid python3 app/notify.py > notify.log 2>&1 < /dev/null &


